stages:
  train_and_evaluate:
    cmd: python scripts/titanic_example.py
    deps:
      - scripts/titanic_example.py
      - data/train.csv
      - data/test.csv
      - params.yaml
    params:
      - num_estimators
    outs:
      - rnf_classifier.pkl
    plots:
      - logs  
