stages:
  train_and_evaluate:
    cmd: python src/titanic_example.py
    deps:
      - src/titanic_example.py
      - data/train.csv
      - data/test.csv
      - params.yaml
    params:
      - num_estimators
    outs:
      - model/rnf_classifier.pkl
    plots:
      - results/plots/metrics:
          x: step
          y: accuracy
    metrics:
    - results/metrics.json