name: CML Workflow

on:
  push:
    branches:
      - main

jobs:
  run-experiment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 

    # Setup Node.js with a current version
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    # Setup Python with a specific version if needed
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run DVC repro
      run: |
        # Assuming DVC is already setup to work with your custom storage
        # and doesn't require any special credentials environment variables.
        dvc pull
        dvc repro

    - name: Push changes
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-email@example.com'
        git checkout -B ${{ github.head_ref }}
        dvc push
        git add .dvc/config
        git commit -m "Run experiment"
        git push origin HEAD:${{ github.head_ref }}
